destination: ./_site
auto:        true
lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   date
excerpt_separator: \#
rdiscount:
  extensions: [smart]
redcarpet:
  extensions: [fenced_code_blocks]
  render_options:
